### ISSUE TITLE
Generic erc20 factory support

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/wc#2]
Could we do a factory that can use an already minted erc20
Send the tokens to the factory and then something like this to transfer instead of minting 

Use token interface instead of a new token and change this
[L72](https://github.com/HausDAO/wc/blob/614f4ded3a792acb8ef81038ad6d157106efb768/contracts/Factory.sol#L72)

to this
```
        // transfer all tokens from this contract
        // probably require there are enough tokens
        distributionToken.transfer(address(this), trust, _dist.trustDist);
        distributionToken.transfer(address(this), transmutation, _dist.transmutationDist);
        // transfer the rest to the minion
        distributionToken.transfer(address(this), minion, distributionToken.balanceOf(address(this)));
```

**Comment by wolflo** [comment]
One issue with this is that anyone can front-run the call to `deployAll` and destroy or steal the tokens transferred to the factory. Ideally, a factory would hold no balances and no power outside of the execution of a single transaction.

We could mitigate this by using `distributionToken.transferFrom(msg.sender, trust/minion/transmutation, amt)`, but this assumes that the caller of `deployAll` holds enough distributionToken to cover the cost of the distributions. We also lose some guarantees about the state of the distribution token (e.g. the minting ability is burned and there are no additional tokens created).
